"
  CREATE TABLE "C##SY94"."BUYER" 
   (	"BUYER_ID" CHAR(6) NOT NULL ENABLE, 
	"BUYER_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"LPROD_GU" CHAR(4) NOT NULL ENABLE, 
	"BUYER_BANK" VARCHAR2(40), 
	"BANK_ACC_NUM" VARCHAR2(40), 
	"ACC_OWNER" VARCHAR2(15), 
	"BUYER_ZIP" CHAR(7), 
	"BUYER_ADD1" VARCHAR2(100), 
	"BUYER_ADD2" VARCHAR2(80), 
	"BUYER_COMTEL" VARCHAR2(14) NOT NULL ENABLE, 
	"BUYER_FAX" VARCHAR2(20), 
	"BUYER_MAIL" VARCHAR2(40), 
	"BUYER_CHARGER" VARCHAR2(10), 
	"BUYER_TELEXT" VARCHAR2(2), 
	 CONSTRAINT "PK_BUYER" PRIMARY KEY ("BUYER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FR_BUYER_LGU" FOREIGN KEY ("LPROD_GU")
	  REFERENCES "C##SY94"."LPROD" ("LPROD_GU") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" "


"
  CREATE TABLE "C##SY94"."BUYPROD" 
   (	"BUY_DATE" DATE NOT NULL ENABLE, 
	"PROD_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"BUY_QTY" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_BUYPROD" PRIMARY KEY ("BUY_DATE", "PROD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FR_BUY_PROD" FOREIGN KEY ("PROD_ID")
	  REFERENCES "C##SY94"."PROD" ("PROD_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" "


"
  CREATE TABLE "C##SY94"."CART" 
   (	"MEM_ID" VARCHAR2(15) NOT NULL ENABLE, 
	"CART_NO" CHAR(13) NOT NULL ENABLE, 
	"PROD_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"CART_QTY" NUMBER(8,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CART" PRIMARY KEY ("CART_NO", "PROD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FR_CART_MEMBER" FOREIGN KEY ("MEM_ID")
	  REFERENCES "C##SY94"."MEMBER" ("MEM_ID") ENABLE, 
	 CONSTRAINT "FR_CART_PROD" FOREIGN KEY ("PROD_ID")
	  REFERENCES "C##SY94"."PROD" ("PROD_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" "


"
  CREATE TABLE "C##SY94"."JAVA_BOARD" 
   (	"NO" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(200), 
	"CONTENT" VARCHAR2(2000), 
	"WRITER" VARCHAR2(20), 
	"DLEYN" VARCHAR2(20) DEFAULT 'N', 
	 CONSTRAINT "JAVA_BOARD_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" "


"
  CREATE TABLE "C##SY94"."JAVA_MEMBER" 
   (	"ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PASS" VARCHAR2(20), 
	"NAME" VARCHAR2(20), 
	 CONSTRAINT "JAVA_MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" "


"
  CREATE TABLE "C##SY94"."LPROD" 
   (	"LPROD_ID" NUMBER(7,0) NOT NULL ENABLE, 
	"LPROD_GU" CHAR(4) NOT NULL ENABLE, 
	"LPROD_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	 CONSTRAINT "PK_LPROD" PRIMARY KEY ("LPROD_GU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" "


"
  CREATE TABLE "C##SY94"."MEMBER" 
   (	"MEM_ID" VARCHAR2(15) NOT NULL ENABLE, 
	"MEM_PASS" VARCHAR2(15), 
	"MEM_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"MEM_REGNO1" CHAR(6), 
	"MEM_REGNO2" CHAR(7), 
	"MEM_BIR" DATE, 
	"MEM_ZIP" CHAR(7), 
	"MEM_ADD1" VARCHAR2(100), 
	"MEM_ADD2" VARCHAR2(80), 
	"MEM_HOMETEL" VARCHAR2(14), 
	"MEM_COMTEL" VARCHAR2(14), 
	"MEM_HP" VARCHAR2(15), 
	"MEM_MAIL" VARCHAR2(40), 
	"MEM_JOB" VARCHAR2(40), 
	"MEM_HOBBY" VARCHAR2(40), 
	"MEM_MEMORIAL" VARCHAR2(40), 
	"MEM_MEMORIALDAY" DATE, 
	"MEM_MILEAGE" NUMBER(10,0), 
	"MEM_DELETE" VARCHAR2(1), 
	 CONSTRAINT "PK_MEM_ID" PRIMARY KEY ("MEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" "


"
  CREATE TABLE "C##SY94"."PROD" 
   (	"PROD_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"PROD_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"LPROD_GU" CHAR(4) NOT NULL ENABLE, 
	"BUYER_ID" CHAR(6) NOT NULL ENABLE, 
	"PROD_COST" NUMBER(10,0) NOT NULL ENABLE, 
	"PROD_PRICE" NUMBER(10,0) NOT NULL ENABLE, 
	"PROD_SALE" NUMBER(10,0), 
	"PROD_OUTLINE" VARCHAR2(100), 
	"PROD_DETAIL" CLOB, 
	"PROD_IMG" VARCHAR2(40), 
	"PROD_TOTALSTOCK" NUMBER(10,0), 
	"PROD_INSDATE" DATE, 
	"PROD_PROPERSTOCK" NUMBER(10,0), 
	"PROD_SIZE" VARCHAR2(20), 
	"PROD_COLOR" VARCHAR2(20), 
	"PROD_DELIVERY" VARCHAR2(255), 
	"PROD_UNIT" VARCHAR2(6), 
	"PROD_QTYIN" NUMBER(10,0), 
	"PROD_QTYSALE" NUMBER(10,0), 
	"PROD_MILEAGE" NUMBER(10,0), 
	 CONSTRAINT "PK_PROD_ID" PRIMARY KEY ("PROD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FR_PROD_LGU" FOREIGN KEY ("LPROD_GU")
	  REFERENCES "C##SY94"."LPROD" ("LPROD_GU") ENABLE, 
	 CONSTRAINT "FR_PROD_BUYER" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "C##SY94"."BUYER" ("BUYER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PROD_DETAIL") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) "


"
  CREATE TABLE "C##SY94"."REMAIN" 
   (	"REMAIN_YEAR" CHAR(4) NOT NULL ENABLE, 
	"PROD_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"REMAIN_J_00" NUMBER(5,0), 
	"REMAIN_I" NUMBER(5,0) DEFAULT 0, 
	"REMAIN_O" NUMBER(5,0) DEFAULT 0, 
	"REMAIN_J_99" NUMBER(5,0) DEFAULT 0, 
	"REMAIN_DATE" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "REMAIN_PK" PRIMARY KEY ("REMAIN_YEAR", "PROD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "REMAIN_FK1" FOREIGN KEY ("PROD_ID")
	  REFERENCES "C##SY94"."PROD" ("PROD_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" "